from typing import List, Optional, Literal
from pydantic import BaseModel, Field, ConfigDict


class BrandBriefPayload(BaseModel):
    """Core brief ingestion payload submitted by user or external client."""
    model_config = ConfigDict(extra="forbid")

    project_id: str = Field(..., description="UUID identifying the workspace project")
    product_name: str = Field(..., max_length=120, description="Name of the product or brand")
    product_url: Optional[str] = Field(None, description="Optional landing page URL for context extraction")
    raw_brief_text: str = Field(..., min_length=20, description="Raw input text describing product positioning & goals")
    target_platform: Literal["tiktok", "instagram_reels", "youtube_shorts"] = Field(
        "instagram_reels", description="Primary video platform format"
    )
    forbidden_terms: List[str] = Field(
        default_factory=list, description="List of forbidden compliance/brand terms"
    )


class AudiencePersona(BaseModel):
    """Synthesized target audience psychographic persona."""
    model_config = ConfigDict(extra="forbid")

    persona_name: str = Field(..., description="Segment identifier name")
    demographic_range: str = Field(..., description="Target demographic range")
    primary_anxiety: str = Field(..., description="Core latent pain point or customer anxiety")
    buying_trigger: str = Field(..., description="Psychographic trigger prompting purchase")
    skepticism_barrier: str = Field(..., description="Primary objection or cause for skepticism")


class StrategistOutput(BaseModel):
    """Guaranteed output artifact from the Strategist Agent."""
    model_config = ConfigDict(extra="forbid")

    personas: List[AudiencePersona] = Field(
        ..., min_length=1, max_length=3, description="List of 1-3 target customer personas"
    )
    core_value_props: List[str] = Field(
        ..., min_length=2, description="At least 2 core value propositions"
    )
    positioning_statement: str = Field(..., description="Strategic positioning summary statement")


class EvaluationVector(BaseModel):
    """Multi-factor heuristic scoring vector generated by the Brand Critic."""
    model_config = ConfigDict(extra="forbid")

    novelty_score: float = Field(..., ge=0.0, le=100.0, description="Pattern disruption & novelty index")
    clarity_score: float = Field(..., ge=0.0, le=100.0, description="Cognitive clarity & single-message focus")
    hook_velocity_score: float = Field(..., ge=0.0, le=100.0, description="First-3-second impact and tension")
    brand_alignment_score: float = Field(..., ge=0.0, le=100.0, description="Compliance & policy alignment")
    composite_index: float = Field(..., ge=0.0, le=100.0, description="Weighted composite score (0-100)")
    pass_audit: bool = Field(..., description="Boolean pass/fail determination (composite >= 80.0)")
    critique_notes: str = Field(..., description="Structured feedback or revision notes")


class SceneStoryboardBeat(BaseModel):
    """Pacing-calibrated script beat for video storyboard."""
    model_config = ConfigDict(extra="forbid")

    beat_number: int = Field(..., ge=1, description="Sequential beat number")
    duration_seconds: float = Field(..., gt=0.0, description="Beat duration in seconds")
    visual_description: str = Field(..., description="Visual scene & camera direction")
    audio_voiceover: str = Field(..., description="Voiceover spoken script")
    on_screen_text: str = Field(..., description="On-screen caption/text overlay")


class CreativeAngleVariant(BaseModel):
    """Divergent creative angle variant artifact."""
    model_config = ConfigDict(extra="forbid")

    variant_id: str = Field(..., description="Unique variant identifier e.g. VAR-A-PAIN-001")
    angle_archetype: Literal["pain_agitation", "value_inversion", "social_proof"] = Field(
        ..., description="Creative angle archetype"
    )
    headline_hook: str = Field(..., description="Attention-capturing headline hook")
    narrative_thesis: str = Field(..., description="Core narrative thesis")
    storyboard: List[SceneStoryboardBeat] = Field(..., min_length=1, description="Beat-by-beat video storyboard")
    evaluation: EvaluationVector = Field(..., description="Brand Critic evaluation vector")
    execution_latency_ms: int = Field(..., ge=0, description="Execution duration in milliseconds")
    token_cost_usd: float = Field(..., ge=0.0, description="Estimated LLM API cost in USD")
